version = 0.1
[default.deploy.parameters]
stack_name = "aws-lambda-springboot-java"
resolve_s3 = true
s3_prefix = "aws-lambda-springboot-java"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
